config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller: { registrations: 'user/registrations'}
  root to:'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stocks', to: 'stocks#search'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  resources :users, only: [:show]
  resources :friendships, only: [:destroy]
  resources :user_stocks, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.search_new_stock(ticker)
    begin
      stock = StockQuote::Stock.quote(ticker)
      searched_stock = Stock.new(ticker: stock.symbol, name:stock.company_name, last_price:stock.close)
    rescue Exception => e
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships

  def already_added?(ticker)
    stock = Stock.find_by_ticker(ticker.upcase)
    return true if (stock && user_stocks.where(stock_id: stock.id).exists?)
    false
  end

  def under_stock_limit?
    user_stocks.count < 10
  end

  def can_add_stock?(ticker)
    !(already_added?(ticker) && under_stock_limit?)
  end

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end

  def self.universe_user_search(params)
    params = params.strip.downcase
    univ_user = User.where('first_name LIKE ?', "%#{params}%")
                    .or(User.where('last_name LIKE ?', "%#{params}%"))
                    .or(User.where('email LIKE ?', "%#{params}%"))
    univ_user
  end

  def exept_current_user(users)
    users.reject {|user| user.id == self.id}
  end



end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @deleting_relationship = Friendship.where(user_id: current_user.id, friend_id: params[:id]).first
    username = User.find_by_id(params[:id]).full_name
    if @deleting_relationship.destroy
      flash[:success] = "Successfully removed #{username} from your list"
    else
      flash[:danger] = "Something wrong with your request, please try it later"
    end
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.search_new_stock(params[:stock])
      if @stock
        respond_to do |format|
          format.js {render partial: 'users/result'}
        end
      else
        respond_to do |format|
        flash.now[:danger] = "We couldn't find the ticker you entered, please enter valid ticker"
        format.js {render partial: 'users/result'}
      end
      end
    else
      respond_to do |format|
        flash.now[:danger] = "Please enter valid input"
        format.js {render partial: 'users/result'}
      end
    end
  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock.nil?
      stock = Stock.search_new_stock(params[:stock_ticker])
      stock.save
    end
    @user_stock = UserStock.create(user:current_user, stock:stock)
    flash[:success] = "Your stock #{@user_stock.stock.name} has been saved!"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find_by_id(params[:id])
    user_stock = UserStock.where(user_id: current_user, stock_id: stock.id).first
    user_stock.destroy
    flash[:success] = "Your stock #{stock.name} has been deleted!"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    if params[:user_finder].blank?
      flash.now[:danger] = "You have entered an empty search string"
    else
      @friends = User.universe_user_search(params[:user_finder])
      @friends = current_user.exept_current_user(@friends)
      flash.now[:danger] = "No users meet this search criteria" if @friends.blank?
    end
    respond_to do |format|
      format.js {render partial: 'friends/result'}
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def add_friend
    @new_friend = Friendship.new(user_id: params[:user_id], friend_id: params[:friend_id])
    if @new_friend.save
      flash[:success] = "You have successfully added a friend."
    else
      flash[:danger] = "There was something wrong with your entry, please try later"
    end
    redirect_to my_friends_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_lookup.html.erb
<h3>Search for Friends</h3>

<div class="" id="friends-lookup">
  <%= form_with url: search_friends_path, method: :get, id: "friends-lookup-form" do |f| %>
    <div class="form-group row no-padding text-center col-xs-12 custom-Friends-search-form">
      <div class="col-sm-9">
        <%= f.text_field :user_finder, placeholder:"Search Friend", autofocus: true,
                                               class:"form-control search-box input-lg" %>
      </div>
      <div class="col-sm-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Look Up a Friend
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="friend-results">
  <%= render 'friends/result' %>
</div>

app/views/friends/_result.html.erb
<% if params[:action] == 'search'  %>
  <div class="search-notification text-center col-xs-12 ">
    <%= bootstrap_flash %>
  </div>
<% end %>

<% if @friends %>
<div class="well results-block col-xs-12 text-center">
  <div class="row">
    <% @friends.each do |friend| %>
    <div class="col-xs-9">
      <strong>E-mail :</strong> <%= friend.email %><br>
      <strong>Name :</strong> <%= friend.full_name %><br>
      <%= link_to "Profile", user_path(friend), class: 'btn btn-xs btn-success' %>
    </div>
    <div class="col-xs-3">
      <% if current_user.friends.include?(friend) %>
         <%= link_to "UNFOLLOW", friendship_path(friend), method: :delete %>
      <% else %>
         <%= link_to "Follow", add_friend_path(user_id: current_user.id, friend_id: friend.id),
                               method: :post%>
      <% end %>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/friends/_result.js.erb
$('#friend-results').html("<%= j (render 'friends/result.html') %>")

app/views/friendships/_list.html.erb
<% if current_user.friends.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="3" class="page-header">
          <h2>My Friends</h2>
        </th>
      </tr>
      <tr>
        <td><strong>Name</strong></td>
        <td><strong>Email</strong></td>
        <td><strong>Actions</strong></td>
      </tr>
    </thead>
    <tbody>
      <% @my_friends.each do |friend| %>
      <tr>
        <td> <%= friend.full_name %></td>
        <td> <%= friend.email %></td>
        <td> <%= link_to "View Profile", user_path(freind.id), class: "btn btn-primary btn-xs" %>
             <%= link_to "Remove Friendship", friendship_path(friend), class: "btn btn-danger btn-xs" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3>You don't have any friends yet, please add some! </h3>

<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <% if current_user %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>FinanceTrackerV2</a>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-4">
          <li><%= link_to "My Portfolio", my_portfolio_path  %></li>
          <li><%= link_to "Edit Profile",  edit_user_registration_path %></li>
          <li><%= link_to "My Friends", my_friends_path  %></li>
        </ul>
        <ul class="nav navbar-right col-md-6">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class="col-md-4 logout">
            <%= link_to "Log out", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTrackerV2" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <%= render partial: 'layouts/navigation' %>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
      </div><!--/row-->

      <footer class="col-xs-12">
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_list.html.erb
<% if @user.stocks.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <td><strong>NAME</strong></td>
        <td><strong>SYMBOL</strong></td>
        <td><strong>CURRENT_PRICE</strong></td>

      </tr>
    </thead>
    <tbody>
      <% @user.stocks.each do |user_stock| %>
      <tr>
        <td> <%= user_stock.name %></td>
        <td> <%= user_stock.ticker %></td>
        <td> $ <%= user_stock.last_price %></td>
        <% if @user.id == @user.id %>
          <td>
            <%= link_to "DELETE FROM PORTFOLIO", user_stock_path(user_stock),
                            class: "btn btn-xs btn-success", method: :delete %>
          </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/_result.html.erb
<% if params[:action] == 'search'  %>
  <div class="search-notification text-center col-xs-12 ">
    <%= bootstrap_flash %>
  </div>
<% end %>
<% if @stock %>
<div class="well results-block col-xs-12 text-center">
  <div class="row">
    <div class="col-xs-9">
      <strong>Symbol:</strong> <%= @stock.ticker %>
      <strong>Name:</strong> <%= @stock.name %>
      <strong>Price:</strong> <%= @stock.last_price %>
    </div>
    <div class="col-xs-3">
      <% if current_user.can_add_stock?(@stock.ticker) %>
      <%= link_to "Add to my portfolio", user_stocks_path(user:current_user, stock_ticker: @stock.ticker),
                                         method: :post, class:"btn btn-xs btn-success" %>
      <% else %>
        <button type="button" name="button" disabled clss="btn btn-xs btn-success">Already Followed</button>
      <% end %>

    </div>
  </div>

</div>
<% end %>

app/views/users/_result.js.erb
$('#search-results').html("<%= j (render 'users/result.html') %>")

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<%= render partial: 'friends/lookup' %>

<% if @friendships.size > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="3" class="page-header">
          <h2>My Friends</h2>
        </th>
      </tr>
      <tr>
        <th><strong>NAME</strong></th>
        <th><strong>Email</strong></th>
        <th><strong>Actions</strong></th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
      <tr>
        <td> <%= friend.full_name %></td>
        <td> <%= friend.email %></td>
        <td>
          <%= link_to 'View Profile', user_path(friend), class: "btn btn-xs btn-success" %>
          <%= link_to "Delete Friend", friendship_path(friend.id),
                            class: "btn btn-xs btn-danger", method: :delete,
                            data: {confirm: "Are You Sure?"}   %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="row col-lg-12">
    <p class="lead">
      You don't have any friends yet, please add some!
    </p>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<h3>Search for Stocks</h3>
<%= flash[:error] if flash[:error] %>
<div class="" id="stock-lookup">
  <%= form_with url: search_stocks_path, method: :get, id: "stock-lookup-form" do |f| %>
    <div class="form-group row no-padding text-center col-xs-12 custom-stock-search-form">
      <div class="col-sm-9">
        <%= f.text_field :stock, placeholder:"Stock Ticker Symbol", autofocus: true,
                                               class:"form-control search-box input-lg" %>
      </div>
      <div class="col-sm-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="" id="search-results">
  <%= render 'result' %>
</div>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h1>User Profile</h1>

<dl class="dl-horizontal">
  <dt>
    <strong>Full Name ::</strong>
  </dt>
  <dd> <%= @user.full_name %> </dd>
  <dt>
    <strong>Email ::</strong>
  </dt>
  <dd> <%= @user.email %> </dd>
</dl>

<% if @user.stocks.any? %>
  <%= render 'stocks/list' %>
<% else %>
  <p class="lead">
    This User is not tracking any stocks
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to stock tracker</h1>


<%= link_to "My Portfolio", my_portfolio_path if current_user%>